name: Generate icon files from icons.json file

on:
  push:
    branches:
      - icon-update-*
    paths:
      - packages/bezier-icons/icons.json

jobs:
  generate-svg:
    name: Generate icon files from icons.json file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Git Config
        run: |
          git config --global user.email "eng@channel.io"
          git config --global user.name "ch-builder"

      - name: Generate Svg files from icons.json
        run: |
          node packages/bezier-icons/scripts/generate-icon-files.js
          git add .
          git commit -m "feat(bezier-icons): generate icon files from icons.json" || echo "skipped commit due to no update"
      
      - name: Delete icons.json files
        run: |
          git rm packages/bezier-icons/icons.json
          git commit -m "feat(bezier-icons): remove icons.json"
          git push
      
      - id: make
        name: Make pr descrition from commit
        run: |
          import os
            name = 'my_name'
            value = 'my_value'
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
          print(f'{name}={value}', file=fh)
      
      - name: echo
        run:  echo "$my_value $my_name"
